1) rewording the usage statement 2) calling coniugationem_sciscere() before the other variables are assigned 3) restructuring coniugationem_sciscere() 4) removing pers/num features based upon conjugation

diff --git a/latina/verbum-temporale/verbum b/latina/verbum-temporale/verbum
--- a/latina/verbum-temporale/verbum
+++ b/latina/verbum-temporale/verbum
@@ -1,22 +1,26 @@
 # -*- mode: Shell-Script;-*-
 
 argument_count=4
-usage="Usus: verbum <a verbo declinatio> (e.g. amo amavi amatus amare)"
+usage="Usus: verbum <a verbo declinatio> (e.g. amō amāvī amātus amāre)"
 
 function coniugationem_sciscere() {
 
     if declinatio::ends_with "$2" "āre"; then
 	echo "1"
-    elif declinatio::ends_with "$1" "eō"; then
+    elif declinatio::ends_with "$2" "ēre"; then
 	echo "2"
     elif declinatio::ends_with "$2" "īre"; then
 	echo "4"
-    else
-	if declinatio::ends_with "$1" "iō"; then
+    elif declinatio::ends_with "$2" "ere"; then
+	if declinatio::ends_with "$1" "iō" ]]; then
 	    echo "3-io"
 	else
 	    echo "3-o"
 	fi
+    else
+	echo "Not valid conjugation type." >&2
+	echo "${usage}" >&2
+	echo "error"
     fi
 
     return 0
@@ -41,12 +45,23 @@ function run {
 	return 1
     fi
 
-    local praes="${1%ō}"
+    coniugatio="$(coniugationem_sciscere "$1" "$4")"
+
+    if [[ "${coniugatio}" == "error" ]]; then
+	return 1
+    fi
+
+    if [[ "${coniugatio}" == "1" || "${coniugatio}" == "3-o" ]]; then
+	local praes="${1%ō}"
+    elif [[ "${coniugatio}" == "3-io" || "${coniugatio}" == "4" ]]; then
+	local praes="${1%iō}"
+    else
+	local praes="${1%eō}"
+    fi
+
     local perf="${2%ī}"
     local pp="$3"
     local inf="$4"
-
-    coniugatio="$(coniugationem_sciscere "${praes}" "${inf}")"
 
     local perf_neu="${pp/%s/m}"
     local fut="${pp/%us/ūrus}"
